name: Sleep for 5 minutes

on:
  pull_request:
 # merge_group:
  push:

jobs:
  validate-pr:
    runs-on: linux
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Display info
      run: | 
        pwd
        ls -al
        git status
    - name: Sleep for 1 minutes
      run: sleep 60
