name: Sleep for 5 minutes

on:
  merge_group:

jobs:
  validate-pr:
    runs-on: linux
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Display info
      run: | 
        pwd
        ls -al
        git status
    - name: Sleep for 5 minutes
      run: sleep 300
