name: Sleep for 5 seconds

on:
  pull_request:

jobs:
  validate-pr:
    runs-on: linux
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Display info
      run: | 
        pwd
        tree -a -I '.git'
        git status
    - name: Sleep for 5 seconds
      run: sleep 5
